JohnMurray/busan

Cargo.toml, build.rs, examples/hello_world/hello_world.proto, examples/hello_world/main.rs, src/actor.rs, src/executor.rs, src/system.rs, src/thread_executor.rs
This change introduces a protobuf library to use with actor initialization
(and eventually message sending). Currently going with `prost`, although
this may change in the future if we decide that more reflection is needed.
Or possibly some additional generation will be needed, we'll see.
With proper message types we can add actor initialization. We rely on the
same type for messages here to help encourage accidental state sharing
on initialization. This will make more sense once the `debug_serialize!`
macro is added.
=> proto actor initialization

.github/workflows/ci.yaml
Adds a GH workflow for some basic CI tests, specifically it adds:
+ `cargo check` - does the lib and all the examples compile okay
+ `cargo test` - runs tests
+ `cargo clippy` - linter for code-quality
Since things are still very much in the prototype'y phase, the linter
is set to allow warnings. Does clippy emit higher values than that?
Anyways, once things become more mature, we can circle back to turning
this on and making it more aggressive (and probably a giant
refactor/cleanup when that happens)
CI is a good thing? A nice status badge is cool.
This _is_ the test plan.
=> Add GitHub Workflows support for some basic CI jobs

examples/hello_world/main.rs, src/executor.rs, src/system.rs, src/thread_executor.rs
+ Refactors the return handle of the executor factory (previously just a
`Sender<ExecutorCommand>`) to be a struct that encapsulates the close
functionality via a `FnOnce`.
+ Implement closing for the existing thread-based executors via
`thread::JoinHandle::join()`
+ Add `await_shutdown()` to the system, which simply calls the `await_close`
method on the `ExecutorHandle`, but doesn't send the command to indicate
a shutdown. This is essentially something that could be called in a `main`
function for a process you want to run indefinitely.
Resolve #8 
Currently no tests 😢, just banking on the fact that this compiles. More
comprehensive testing will come at a later stage.
=> Implement system shutdown (properly)

Cargo.toml, examples/hello_world/main.rs, examples/ping_pong/main.rs, src/actor.rs, src/executor/mod.rs, src/executor/thread_executor.rs, src/system.rs
This commit adds the ability of actors to spawn other actors given a context object that is internally wired up to the current executor. The title says "basic" for a few different reasons:
+ It is possible to create children in a loop and deadlock the executor
+ Children are created async and it's not currently possible to create + 'ask'
without hittig a deadlock. (not that asking is supported yet anyways)
+ There is no link created between parent and child, because there is no lifecycle
support and messages can't be sent anyways.
Resolves #9
A new example was added that manually validates the new functionality.
=> Basic child-actor creation

examples/hello_world/main.rs, examples/ping_pong/main.rs, src/executor/mod.rs, src/executor/thread_executor.rs, src/lib.rs, src/system.rs, src/util.rs
+ Introduces a runtime manager for coordinating amongst executors
+ Updates executors to defer to runtime manager for actor assignment
+ Runtime manager assigns actors to executors based on round-robin strategy
Note: It's still possible for an executor to assign the actor back to the originating executor. Need to think on this if that's a problem for now-me or future-me.
Resolves #28
Per the changes introduced in #25, actor creation is currently a blocking operation. That is, an actor may create an actor and then perform work indefinitely in it's receive block, including sending messages to the created actor. Until the actor yields, the child actor would not be created.
This is not ideal, particularly when future patterns such as `ask` are introduced, this creates potential for deadlock. …
=> Non-Blocking Actor Spawn

src/actor.rs, src/executor/mod.rs, src/executor/thread_executor.rs, src/system.rs
__Implement `ActorAddress` resolution__
Added a method to the `RuntimeManagerRef` that can communicate with the management thread in a pseudo-blocking mechanism (only blocks the calling thread) in order to perform address resolution.
This should be sufficient once implementing message sending to locate the right place to send a message and cache the `Sender` in the `ActorAddress`.
__Implementing `ActorCell` and basic addressing__
+ Commands issued from management thread now package up assignment details (actor, address, mailbox) into an `ActorCell`.
+ Addresses are defined as heirarchical and created locally to where the actor is created.
+ Addresses updated with internal state to cache the `Sender` once the address is "resolved"
+ Global lookup of address -> mailbox added to the …
=> Implement address, address resolution, and actor-cell

CHANGELOG.md, examples/hello_world/main.rs, examples/ping_pong/main.rs, src/actor.rs, src/message/common_types.rs, src/message/mod.rs, src/system.rs
Implement method unwrapping and pattern matching by making use of the `Any` type. In order to make this work, I needed a way to cast a trait-object (`Box<dyn prost::Message>`) into Any so that I can pattern-match against concrete types. I accomplished this by replacing the use of `prost::Message` with my own `Message` trait that had a method `as_any(&self) -> &Any` (and using `prost::Message` as a super-trait).
This works and allows for type-safe, runtime pattern matching.
#11
Currently relying on the example projects to test (they compile and I run them manually to validate).
A few thoughts after working through this implementation:
+ Need to land the derive proc-macro
+ Having to implement `Message` is a bit of a joke, it has a method that is always the same
+ I have this locally, but …
=> Message unwrapping/pattern matching

.gitignore, CHANGELOG.md, Cargo.toml, busan-derive/Cargo.toml, busan-derive/README.md, busan-derive/src/lib.rs, examples/hello_world/build.rs, examples/hello_world/src/main.rs, examples/ping_pong/src/main.rs, src/lib.rs, todo.md
Adds a new package `busan-derive` that defines a derive proc-macro for deriving implementations of `busan::messages::Message`.
Updates the `hello_world` example to make use of the macro by adding it to generated code created in `build.rs`.
#11
The `Message` trait is a requirement for pattern matching, but is an _additional_ trait on top of `prost::Message` (or possibly some other serialization trait), and there are already patterns for generating code with prost (either via `prost-derive` or `prost-build` packages).
Having a derive macro allows users the same flexibility to either use the macro directly, or do define an additional macro be inserted on generated code.
CI is sufficient as the `hello_world` examples makes use of the new compile-time features.
=> Derive proc-macro for busan::message::Message

Cargo.toml, src/actor/actor.rs, src/actor/address.rs, src/actor/mod.rs, src/config.rs, src/executor/mod.rs, src/lib.rs, src/message/mod.rs, src/prelude.rs, src/system.rs, src/util.rs
+ Cleanup `Cargo.toml` for the main project
+ Add `prelude` module
+ Add docs for the `ActorSystem` and root module
+ Add docs for the `actor` module
#51
Validated locally with generated rustdoc. CI validates for spelling errors.
=> 0.2.0 Code Review - Cleanup & Docs

examples/hello_world/src/main.rs, examples/ping_pong/src/main.rs, src/actor/actor.rs, src/actor/mod.rs, src/system.rs
Use `ToMessage<M>` when creating an actor.
+ Matches the API for sending messages
+ Additional ergonomic benefits to values passed in, particularly for primitives.
This has an ergonomics _cost_, however, in the signature now having three generics. Adding this to my punch-list of ergonomics issues to revisit later.
+ [x] Examples
+ [x] doc-tests (more examples)
=> actor creation - use ToMessage<M>

.github/workflows/cspell.json, README.md, examples/ping_pong/Cargo.toml
Rephrase the documentation section in the README now that the docs.rs stuff is semi-useful. Also add some bits on how to run the examples since I think that's going to be a decent place to look at code going forward and I expect to add more examples.
Add a section regarding the license at the bottom. I'm not sure if the GPLv3 is super popular and folks may not expect it, so worth pointing out.
README.md was lagging a bit behind the project.
Spell check in CI
=> Update documentation and licensing info in README.md

busan-derive/src/lib.rs, src/message/common_types.rs, src/message/mod.rs
Add `merge2` to `Message` which is a wrapper to `prost::Message::merge`. Added as an undocumented (hidden) method on Message that is primarily an implementation detail internal to busan.
The `Message::merge` function from prost requires that self be `Sized`. `merge2` allows us to call the merge function through dynamic dispatch by implementing `merge2` on the object and not in the trait.
It compiles. Usages will come later for further testing/refinement.
=> add merge2 to busan::message::Message

examples/ping_pong/src/main.rs, src/actor/actor.rs
Split message sending into two methods:
+ `Context::send` - Utility method that takes `ToMessage`, performs conversion and calls `Context::send_message`
+ `Context::send_message` - Takes a `Box<Message>`, resolves the address, performs serialization/deserialization (in debug mode), and transmits the message.
The previous implementation of `send_message` worked by using `ToMessage` as a convenience type to cut down on the boilerplate of sending messages. This worked great, however it had one drawback in that is relied on concrete types.
The ability to also send a `Box<Message>` allows for patterns, abstractions, or middle-men to be built. Take a load-balancer actor for example. It receives `Box<Message>`s and then forwards them to an actor in a pool. In this instance, there is no concrete …
=> Split message sending into two (complementary) methods

build.rs, src/actor/address.proto, src/actor/address.rs, src/actor/mod.rs, src/actor/proto.rs, src/message/common_types.rs
More or less what the title says. This PR adds the proto messages and necessary trait implementations to send an `ActorAddress` (or a slice of them) as a `busan::message::Message`.
In theory this means they can be serialized and shared across process boundaries, but in reality that would require a bit more work as nothing other than the "local" scheme is supported at the moment.
Sharing addresses unlocks more dynamic messaging patterns as currently it's only possible to send messages between parents and children.
Nothing ATM. Work on load balancing will make use of and test this further.
=> support sending ActorAddress objects

src/actor/actor.rs, src/executor/mod.rs, src/executor/thread_executor.rs
Adds an initial `shutdown` message to the actor context. This allows an actor to immediately shutdown (only callable from within the actor) and sets some state on the actor so that no new messages are received.
Part of #29.
This is only a small subset of actor shutdown logic, see #29 for full details.
Still TBD. I'll see how this evolves as shutdown evolves over the course of implementing #29.
=> [actor shutdown] Context method + no-deliver state

src/executor/thread_executor.rs
Introduces a new `context!` macro in thread_executor that just makes constructing context objects less visually intrusive (8 lines per instantiation!). Code is much easier to read now.
Part of #29.
The changes for actor shutdown will introduce more instances in which a context object will be created from a system context. It made sense to invest in a macro here to save some typing. Took a few iterations to get this working right (so many TIL moments).
If it compiles it's good. This change should be functionally equivalent to what existed before.
=> [actor shutdown] Add a context macro to thread_executor

src/executor/thread_executor.rs
Fix the loop in the thread executor to only sleep when no work has been done on an iteration. Because only one message per actor is processed per loop (for fairness or whatever), it's very possible/likely for there to be more message waiting. In those instances, we don't need to sleep.
Found this issue while working on #29. We shouldn't sleep when there is still work to be done (potentially). Even though the thread-executor will eventually be replaced with a tokio runtime, should still fix this up.
Existing examples thoroughly exercise this.
=> [thread_executor] Fix thread sleep in work loop

src/actor/actor.rs, src/executor/thread_executor.rs
Add two hooks on the `Actor` type, `before_stop` and `after_stop`. These methods allow final cleanup code and message-sending during the shutdown process.
Part of #29.
Actors need a mechanism to perform final cleanup operations on shutdown.
TBD. Further evolution on the shutdown process will determine the overall testing strategy.
=> [actor shutdown] shutdown hooks

src/executor/thread_executor.rs, src/system.rs
Propegates shutdown signals to children via the runtime manager. Currently there is no coordination between timing/ordering of parents and children except for the flow of initial messages. That is to say that the actual moment in which actors are removed from the runtime queue and the `before`/`after_stop` methods are finished may race. I think this is a fine trade-off for now. Coordination is a lot trickier, and possibly not necessary.
Part of #29.
Actors are organized in heirarchical trees. In an actor system, all actors should be part of the same tree and thus if an actor shuts down and has children, the shutdown signals have to propegate down the tree.
TBD. Will address testing as the final step in impelemnting actor shutdown.
=> [actor shutdown] shutdown children

.github/workflows/cspell.json, src/actor/actor.rs, src/executor/thread_executor.rs
When an actor shuts down, the state bitmask in the `ActorCell` is flipped from the `Context` object when a shutdown is requested. Previously this was only set within the executor.
Part of #29 
There is an asynchronous delay between an actor signaling it is shutting down to when the executor sets the state. This is because the request travels through the runtime manager and then back to the executor via async channel communications.
What is described above introduces a window where an actor has signaled shutdown and continues to receive messages. By setting the shutdown flag directly within the actor (as well as within the executor), messages processing by the actor will stop immediately.
Shutdown testing will be covered in the broader actor shutdown effort.
=> [actor shutdown] cell state bitmask fix
